services:
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=hamid'
      - 'RABBITMQ_DEFAULT_PASSWORD=hamidgharib'
    ports:
      - '5672:5672'
      - '15672:15672'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=managementsystem'
      - 'MYSQL_PASSWORD=Hamid72'
      - 'MYSQL_ROOT_PASSWORD=Hh@102030'
      - 'MYSQL_USER=hamid'
    ports:
      - '3306:3306'
