services:
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbitmq_net
  docker-mysql:
    image: 'mysql:8.3.0'
    environment:
      - 'MYSQL_DATABASE=managementsystem'
      - 'MYSQL_PASSWORD=Hamid72'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=hamid'
      - 'MYSQL_URL=jdbc:mysql://localhost:3306/managementsystem'
    ports:
      - '3306:3306'
    networks:
      - mysql_net

networks:
    rabbitmq_net:
      driver: bridge
    mysql_net:
      driver: bridge