spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: inventory-system
            uri: ${INVENTORY_URI:http://localhost:8090}
            predicates:
              - Path=/inventory/**
            filters:
              - PrefixPath=/v1
              - AddResponseHeader=X-Powered-By,Management system

          - id: order-system
            uri: ${ORDER_URI:http://localhost:8060}
            predicates:
              - Path=/order/**
            filters:
                  - PrefixPath=/v1
                  - AddResponseHeader=X-Powered-By,Management system

          - id: shipping-system
            uri: ${SHIPPING_URI:http://localhost:8040}
            predicates:
              - Path=/shipping/**
            filters:
              - PrefixPath=/v1
              - AddResponseHeader=X-Powered-By,Management system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/managementsystem?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: hamid
    password: Hamid72
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8030
